### ISSUE TITLE
有java版本的吗  我还不太熟kotlin

### ISSUE THREAD

**Issue by zz005** [kongpf8848/Animation#2]
有java版本的吗  我还不太熟kotlin

**Comment by kongpf8848** [comment]
很久之前是java，后来转成kotlin了，你可以根据log日志将版本回退到之前的java版本。
![20210810_200925](https://user-images.githubusercontent.com/25379134/128864793-4fc438f4-4549-4808-8294-d6e4e5ad20ac.jpg)

**Comment by zz005** [comment]
哦 谢谢大佬
